<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="250" started-at="2021-04-09T08:08:19Z" finished-at="2021-04-09T08:08:20Z">
    <groups>
      <group name="reg">
        <method signature="DependsOnGroups.tc0()[pri:0, instance:org.cts.DependsOnGroups@cb5822]" name="tc0" class="org.cts.DependsOnGroups"/>
      </group> <!-- reg -->
      <group name="smoke">
        <method signature="DependsOnGroups.tc3()[pri:0, instance:org.cts.DependsOnGroups@cb5822]" name="tc3" class="org.cts.DependsOnGroups"/>
      </group> <!-- smoke -->
      <group name="sanity">
        <method signature="DependsOnGroups.tc1()[pri:0, instance:org.cts.DependsOnGroups@cb5822]" name="tc1" class="org.cts.DependsOnGroups"/>
      </group> <!-- sanity -->
      <group name="E2E">
        <method signature="DependsOnGroups.tc3()[pri:0, instance:org.cts.DependsOnGroups@cb5822]" name="tc3" class="org.cts.DependsOnGroups"/>
      </group> <!-- E2E -->
      <group name="retest">
        <method signature="DependsOnGroups.tc4()[pri:0, instance:org.cts.DependsOnGroups@cb5822]" name="tc4" class="org.cts.DependsOnGroups"/>
      </group> <!-- retest -->
    </groups>
    <test name="Test" duration-ms="250" started-at="2021-04-09T08:08:19Z" finished-at="2021-04-09T08:08:20Z">
      <class name="org.cts.DependsOnGroups">
        <test-method status="FAIL" signature="tc0()[pri:0, instance:org.cts.DependsOnGroups@cb5822]" name="tc0" duration-ms="109" started-at="2021-04-09T13:38:19Z" finished-at="2021-04-09T13:38:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at org.cts.DependsOnGroups.tc0(DependsOnGroups.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc0 -->
        <test-method status="PASS" signature="tc3()[pri:0, instance:org.cts.DependsOnGroups@cb5822]" name="tc3" duration-ms="0" started-at="2021-04-09T13:38:20Z" finished-at="2021-04-09T13:38:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc3 -->
        <test-method status="PASS" signature="tc4()[pri:0, instance:org.cts.DependsOnGroups@cb5822]" name="tc4" duration-ms="0" started-at="2021-04-09T13:38:20Z" finished-at="2021-04-09T13:38:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc4 -->
        <test-method status="SKIP" signature="tc1()[pri:0, instance:org.cts.DependsOnGroups@cb5822]" name="tc1" duration-ms="0" depends-on-groups="reg" started-at="2021-04-09T13:38:20Z" finished-at="2021-04-09T13:38:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DependsOnGroups.tc1()[pri:0, instance:org.cts.DependsOnGroups@cb5822] depends on not successfully finished methods in group "reg"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DependsOnGroups.tc1()[pri:0, instance:org.cts.DependsOnGroups@cb5822] depends on not successfully finished methods in group "reg"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1028)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc1 -->
      </class> <!-- org.cts.DependsOnGroups -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
